import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Home,
  Image,
  Info,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogOut,
  type LucideIcon,
  Menu,
  Moon,
  MoreVertical,
  Plus,
  RefreshCcw,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  SunMedium,
  Trash,
  Twitter,
  User,
  UserPlus,
  Users,
  X,
  Building2,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  login: LogOut,
  logout: LogOut,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  user: User,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  alert: AlertTriangle,
  warning: AlertTriangle,
  help: HelpCircle,
  info: Info,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  home: Home,
  dashboard: LayoutDashboard,
  security: ShieldCheck,
  admin: Building2,
  users: Users,
  newUser: UserPlus,
  error: AlertTriangle,
  check: Check,
  shield: Shield,
  shieldAlert: ShieldAlert,
  shieldOff: ShieldOff,
  menu: Menu,
  refresh: RefreshCcw,
  social: {
    twitter: Twitter,
  },
  arrowRight: ArrowRight,
} as const;

export type IconKey = keyof typeof Icons;